fixtures:
  repositories:
    'firewall': 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    'xinetd': 'git://github.com/puppetlabs/puppetlabs-xinetd.git'
  symlinks:
    "tftp": "#{source_dir}"
